steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --- STEP 1: Deploy Global Infrastructure ---
      - name: 'Terraform Init (Global)'
        # Remove the "./" and just use the folder name
        working-directory: global-init
        run: terraform init -backend-config="key=global.tfstate"

      - name: 'Terraform Apply (Global)'
        working-directory: global-init
        run: terraform apply -auto-approve

      # --- STEP 2: Deploy Kiewit-1 Dev ---
      - name: 'Terraform Init (Kiewit-1 Dev)'
        # Ensure this matches your path: projects -> kiewit-1 -> dev
        working-directory: projects/kiewit-1/dev
        run: terraform init -backend-config="key=kiewit1-dev.tfstate"

      - name: 'Terraform Apply (Kiewit-1 Dev)'
        working-directory: projects/kiewit-1/dev
        run: terraform apply -auto-approve