name: 'Kiewit Platform Deploy'

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init (Global)'
        working-directory: ${{ github.workspace }}/global-init
        run: terraform init -backend-config="key=global.tfstate"

      - name: 'Terraform Apply (Global)'
        working-directory: ${{ github.workspace }}/global-init
        run: terraform apply -auto-approve

      - name: 'Terraform Init (Kiewit-1 Dev)'
        working-directory: ${{ github.workspace }}/projects/kiewit-1/dev
        run: terraform init -backend-config="key=kiewit1-dev.tfstate"

      - name: 'Terraform Apply (Kiewit-1 Dev)'
        working-directory: ${{ github.workspace }}/projects/kiewit-1/dev
        run: terraform apply -auto-approve